### PR TITLE
WIP: add performance_test real-time settings tutorial

### PR DESCRIPTION
**Pull request by carlossvg**

### CODE REVIEW

**Comment by carlossvg** [comment]
I created a tutorial to run `peformance_test`  with real-time settings in an RPI4. It's not ready to merge cause we should define the correct kernel settings and update the tutorial with the new configuration. 

You can build the tutorial locally and provide some feedback if you want. 

Some issues I found while creating the tutorial:
- perf test build hangs on rolling
- Using stress-ng with the sequence option is not optimal cause for certain stressor we get bad results. This can be observed if we increase the test duration to 10 minutes. This happens with cyclictest too. This means that either the kernel configuration has to be tuned or that some stressors will impact the application despite the settings used. 
- I didn't use CPU affinity. This will make more sense if we move all the interrupts to CPU 0. As it's done in https://github.com/hsgwa/ros2_timer_latency_measurement/blob/master/setup.md


FYI @LanderU @razr @SniderThanYou

**Comment by christophebedard** [comment]
Somewhat relevant: it should be noted that, currently, some of `performance_test`'s RT configuration code will just silently not be executed by default https://gitlab.com/ApexAI/performance_test/-/merge_requests/232

**Comment by carlossvg** [comment]
> Somewhat relevant: it should be noted that, currently, some of `performance_test`'s RT configuration code will just silently not be executed by default https://gitlab.com/ApexAI/performance_test/-/merge_requests/232

Good catch. We should probably throw an exception if the real-time settings are used.

**Comment by christophebedard** [comment]
> Good catch. We should probably throw an exception if the real-time settings are used.

Oh, good idea!

**Comment by carlossvg** [comment]
@christophebedard I would like to include here some instructions to analyze performance test with ros2 tracing, as you did in your presentation. Could you help me to document the steps you followed and maybe provide some scripts?

**Comment by christophebedard** [comment]
@carlossvg sorry for the late response!

> @christophebedard I would like to include here some instructions to analyze performance test with ros2 tracing, as you did in your presentation. Could you help me to document the steps you followed and maybe provide some scripts?

I'm not sure what presentation you're referring to, are you referring to this? https://gitlab.com/ApexAI/performance_test/-/tree/instrumentation

**Comment by carlossvg** [comment]
> I'm not sure what presentation you're referring to, are you referring to this? 

Yeah, that's one part of what I was looking for.

The other part are the script and or instructions to reproduce the analysis you do in slides 19, 20 ,21 in the ROScon FR2021 presentation. I would like to convert this into a tutorial, I think it would be nice to have. Not only for performance test but as a base for the ros2 control demo we are planning for the ROScon workshop.

**Comment by christophebedard** [comment]
> The other part are the script and or instructions to reproduce the analysis you do in slides 19, 20 ,21 in the ROScon FR2021 presentation. I would like to convert this into a tutorial, I think it would be nice to have. Not only for performance test but as a base for the ros2 control demo we are planning for the ROScon workshop.

I didn't use performance_test in this presentation* (well, other than for the benchmark slide!).

Slide 21 is unrelated to ROS 2. As I mentioned a few weeks ago I'd like to apply that kind of analysis to ROS 2, but it's still a WIP. I'll for sure prepare a tutorial if it's ready in time for ROSCon :grin: 

Slides 19-20 are basically this, but summarized/shortened: https://gitlab.com/ros-tracing/tracetools_analysis/-/blob/master/tracetools_analysis/analysis/callback_duration.ipynb. That's a good idea, I could prepare a tutorial and use performance_test instead of the "pingpong" launch file used there. What should it cover? From building ROS 2 with tracing/LTTng all the way to running the analysis script?

*I used that performance_test branch for the work I did as part of my internship in 2019, I think you can find my presentation somewhere in the Apex.AI Drive.

**Comment by carlossvg** [comment]
> That's a good idea, I could prepare a tutorial and use performance_test instead of the "pingpong" launch file used there. What should it cover? From building ROS 2 with tracing/LTTng all the way to running the analysis script?

Thanks! This would be great. As regards the build instructions, I think it's more complex than usual for a PREEEMPT_RT kernel (I already tried this in the RPI with no luck). I think @LanderU can comment on this.

**Comment by christophebedard** [comment]
> Thanks! This would be great. As regards the build instructions, I think it's more complex than usual for a PREEEMPT_RT kernel (I already tried this in the RPI with no luck). I think @LanderU can comment on this.

Wait shouldn't this be two separate tutorials? Like 1) Setting up a PREEMPT_RT kernel, 2) tracing and analysis.

**Comment by carlossvg** [comment]
> Wait shouldn't this be two separate tutorials? Like 1) Setting up a PREEMPT_RT kernel, 2) tracing and analysis.

Yes, but in this case I installing lttng in a PREEMPT_RT kernel using apt won't work AFAIK. I think you will have to do something specific for the kernel you're using (Lander sent me this link here https://github.com/lttng/lttng-modules/blob/master/scripts/rt-patch-version.sh). 
 
One thing we could do is to split this in separate documents. Maybe explain how to do this in a tutorial next in the "Setting up a PREEMPT_RT kernel section" or maybe directly in ros2 tracing documentation as additional instructions. Then we would just refer to these instructions in the performance test tutorial.

**Comment by christophebedard** [comment]
> Yes, but in this case I installing lttng in a PREEMPT_RT kernel using apt won't work AFAIK. I think you will have to do something specific for the kernel you're using (Lander sent me this link here [https://github.com/lttng/lttng-modules/blob/master/scripts/rt-patch-version.sh](https://github.com/lttng/lttng-modules/blob/master/scripts/rt-patch-version.sh?rgh-link-date=2021-07-14T20%3A39%3A07Z)).

ah I see. I haven't tried that yet. But for the callback durations example there is no need for kernel tracing. So for now we can start with userspace tracing only, that works fine. The more advanced analysis that I'm working on will require kernel tracing, but we're not there yet :stuck_out_tongue: 

> One thing we could do is to split this in separate documents. Maybe explain how to do this in a tutorial next in the "Setting up a PREEMPT_RT kernel section" or maybe directly in ros2 tracing documentation as additional instructions. Then we would just refer to these instructions in the performance test tutorial.

makes sense.

**Comment by carlossvg** [comment]
>ah I see. I haven't tried that yet. But for the callback durations example there is no need for kernel tracing

Good point, I think we can start using user space tracing for the tutorial.

> The more advanced analysis that I'm working on will require kernel tracing, but we're not there yet 

Sounds promising!

**Comment by christophebedard** [comment]
@carlossvg I opened an issue for the `ros2_tracing` tutorial as we discussed above https://github.com/ros-realtime/rtwg_documentation/issues/36 (since this PR is for something else).

**Review by razr — APPROVED** [review]

**Pull request closed without merging**
