### PR TITLE
Update roadmap

### PR DESCRIPTION
**Pull request by carlossvg**
- Add new issue links
- Re-order columns
- Assign tasks
- Fix typos

### CODE REVIEW

**Comment by carlossvg** [comment]
Formatted table: https://github.com/ros-realtime/rtwg_documentation/blob/0d4e82379e24beb15d5d1a09ededcaf1abbc96e0/source/Roadmap/Roadmap.md

**Comment by carlossvg** [comment]
@razr @LanderU Could you review this?

**Review by LanderU — APPROVED** [review]
LGTM!

**Comment by LanderU** [comment]
Thanks a lot!

**Review by razr — APPROVED** [review]

**Pull request merged**
