### PR TITLE
Remove duplicated documents

### PR DESCRIPTION
**Pull request by carlossvg**
I realize that we had some documents duplicated. This PR removes them.

### CODE REVIEW

**Review by razr — APPROVED** [review]

**Comment by carlossvg** [comment]
Let's merge this one after https://github.com/ros-realtime/rtwg_documentation/pull/18 to avoid conflicts

**Review by LanderU — APPROVED** [review]
LGTM!

**Comment by LanderU** [comment]
@carlossvg, would you fix the conflicts?

**Comment by carlossvg** [comment]
> @carlossvg, would you fix the conflicts?

Done

**Pull request merged**
